name: food_ordering_app
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  another_carousel_pro:
    git:
      url: https://github.com/iamnabink/another_carousel_pro.git

  cached_network_image: ^3.1.0
  animated_splash_screen: ^1.1.0
  flutter_spinkit: ^5.0.0
  cupertino_icons: ^1.0.2
  url_launcher: ^6.0.10
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.9.2
  font_awesome_flutter: ^9.1.0
  like_button: ^2.0.2
  google_fonts: ^2.1.0
  flutter_svg: ^0.22.0
  http: ^0.13.3
  provider: ^5.0.0
  after_layout: ^1.1.0
  badges: ^2.0.1
  webview_flutter: ^2.0.12
  open_settings: ^2.0.2
  fluttertoast: ^8.0.8
  lottie: ^1.2.1
dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo.jpg"

flutter:
  uses-material-design: true

  assets:
    - assets/images/
